import type {
  AIReport,
  ControlOrderDraft,
  DiaryImportance,
  FarmDiaryEntry,
  WorkType,
} from "./types";

export const WORK_TYPE_LABELS: Record<WorkType, string> = {
  irrigation: "관수",
  fertilizer: "비료",
  pestControl: "방제",
  harvest: "수확",
  pruning: "전정",
  inspection: "점검",
  diseasePest: "병해충",
  anomaly: "이상상황",
  other: "기타",
};

export const DIARY_IMPORTANCE_LABELS: Record<DiaryImportance, string> = {
  low: "낮음",
  normal: "보통",
  high: "높음",
  urgent: "긴급",
};

/** 농사일지 폼 — 관련 센서 선택 (목업 옵션) */
export const MOCK_DIARY_SENSOR_OPTIONS: { id: string; label: string }[] = [
  { id: "s-temp", label: "온도 (실내)" },
  { id: "s-hum", label: "습도" },
  { id: "s-soil", label: "토양 수분" },
  { id: "s-ec", label: "배액 EC" },
  { id: "s-ph", label: "배액 pH" },
  { id: "s-solar", label: "일사량" },
  { id: "s-co2", label: "CO₂ (예정)" },
];

/** 농사일지 폼 — 관련 장비 선택 (목업 옵션) */
export const MOCK_DIARY_EQUIPMENT_OPTIONS: { id: string; label: string }[] = [
  { id: "eq-irr", label: "관수 밸브" },
  { id: "eq-sky", label: "천창 구동기" },
  { id: "eq-side", label: "측창 구동기" },
  { id: "eq-flow", label: "유동팬" },
  { id: "eq-hot", label: "온풍기" },
  { id: "eq-spray", label: "분무기" },
  { id: "eq-alarm", label: "알람·임계 설정" },
];

export const MOCK_FARM_DIARY_ENTRIES: FarmDiaryEntry[] = [
  {
    id: "fd-001",
    date: "2026-05-04",
    time: "08:30",
    greenhouseId: "gh-03",
    greenhouseName: "제3동 · 딸기",
    crop: "일장형 · 개화기",
    workType: "irrigation",
    description: "A구역 관수 12분. 배액 EC 안정.",
    operator: "김운영",
    photos: [],
    relatedSensorIds: ["s-ec", "s-temp"],
    relatedSensorLabels: ["배액 EC", "온도 (실내)"],
    relatedEquipmentIds: ["eq-irr"],
    relatedEquipmentLabels: ["관수 밸브"],
    importance: "normal",
    aiAnalysisTarget: true,
    createdAt: "2026-05-04T08:31:00.000Z",
  },
  {
    id: "fd-002",
    date: "2026-05-04",
    time: "10:15",
    greenhouseId: "gh-05",
    greenhouseName: "제5동 · 생야채(NFT)",
    crop: "버터헤드 · 5주차",
    workType: "pestControl",
    description: "진딧물 방제 — 친환경제. 잎 등 확인.",
    operator: "이방제",
    photos: [],
    relatedSensorIds: ["s-hum", "s-temp"],
    relatedSensorLabels: ["습도", "온도 (실내)"],
    relatedEquipmentIds: ["eq-spray"],
    relatedEquipmentLabels: ["분무기"],
    importance: "high",
    aiAnalysisTarget: true,
    createdAt: "2026-05-04T10:16:00.000Z",
  },
  {
    id: "fd-003",
    date: "2026-05-04",
    time: "14:00",
    greenhouseId: "gh-07",
    greenhouseName: "제7동 · 시험재배",
    crop: "시험 · DLI 맵",
    workType: "anomaly",
    description: "서편 센서 대비 온도 편차 큼. 통풍 점검.",
    operator: "박점검",
    photos: [],
    relatedSensorIds: ["s-temp", "s-solar"],
    relatedSensorLabels: ["온도 (실내)", "일사량"],
    relatedEquipmentIds: ["eq-side", "eq-flow"],
    relatedEquipmentLabels: ["측창 구동기", "유동팬"],
    importance: "urgent",
    aiAnalysisTarget: true,
    createdAt: "2026-05-04T14:02:00.000Z",
  },
  {
    id: "fd-004",
    date: "2026-05-03",
    time: "16:40",
    greenhouseId: "gh-02",
    greenhouseName: "제2동 · 토마토",
    crop: "방울토마토 · 11주차",
    workType: "fertilizer",
    description: "추비 — 과실 비대기. 관수 직후.",
    operator: "김운영",
    photos: [],
    relatedSensorIds: ["s-ec", "s-ph"],
    relatedSensorLabels: ["배액 EC", "배액 pH"],
    relatedEquipmentIds: ["eq-irr"],
    relatedEquipmentLabels: ["관수 밸브"],
    importance: "normal",
    aiAnalysisTarget: false,
    createdAt: "2026-05-03T16:42:00.000Z",
  },
];

export const MOCK_AI_OPERATION_REPORT: AIReport = {
  id: "air-001",
  generatedAt: "2026-05-04T15:00:00.000Z",
  todayHighlights: [
    "제3동 관수·EC 안정 기록 2건 — 패턴 양호",
    "제5동 방제 작업 1건 — 습도 상승 구간과 시간대 인접",
    "제7동 이상상황 1건 — 온도 편차·일사 상관 요약 완료",
  ],
  anomalySignals: [
    "제7동 실내 온도 편차 > 2.5°C (서편 vs 중앙 추정)",
    "제5동 방제 직후 습도 변화율이 평일 평균 대비 높음",
  ],
  recurringIssues: [
    "오후 일사 급변 시 측창·팬 수동 개입 기록이 주 2회 이상 반복",
    "급수 탱크 잔량 낮은 동(목업)에서 관수·알람 교차 언급",
  ],
  sensorWorkCorrelations: [
    "방제(분무) ↔ 습도 급상승 — 제5동 fd-002와 s-hum 추세 인접",
    "이상상황 ↔ 측창·유동팬 점검 — 제7동 fd-003와 풍량·환기 기록 연결",
    "관수 ↔ EC 안정 — 제3동 fd-001와 s-ec 범위 유지",
  ],
  recommendedActions: [
    "제7동 환기 체계 자동화 조건 재검토 (측창·유동팬)",
    "방제 스케줄과 분무기 ON 시간 분리 검토",
    "급수 탱크 잔량 알람 임계 하향 여부 점검",
  ],
  greenhousesNeedingAttention: ["제7동 · 시험재배", "제5동 · 생야채(NFT)"],
};

export const MOCK_CONTROL_ORDER_DRAFTS: ControlOrderDraft[] = [
  {
    id: "cod-001",
    targetGreenhouseId: "gh-03",
    targetGreenhouseName: "제3동 · 딸기",
    targetEquipment: "관수",
    proposedCommand: "관수 구간 08:00 시작 → 07:40으로 20분 앞당김 (EC 안정 구간 확보)",
    reason: "일지 fd-001 및 최근 EC 변동 최소 시간대와 정합",
    relatedDiaryEntryIds: ["fd-001"],
    relatedSensorSnapshot: "EC 1.35–1.42 mS/cm (목업)",
    riskLevel: "low",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-002",
    targetGreenhouseId: "gh-05",
    targetGreenhouseName: "제5동 · 생야채(NFT)",
    targetEquipment: "천창",
    proposedCommand: "천창 개방 시작 조건: 실내 온도 ≥ 24.0°C (현재 23.5°C 기준에서 완화)",
    reason: "방제 후 습도·온도 교차 — 일지 fd-002",
    relatedDiaryEntryIds: ["fd-002"],
    relatedSensorSnapshot: "습도 72→78% (방제 직후 목업)",
    riskLevel: "medium",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-003",
    targetGreenhouseId: "gh-05",
    targetGreenhouseName: "제5동 · 생야채(NFT)",
    targetEquipment: "측창",
    proposedCommand: "측창 개방 풍속 하한 0.8 m/s → 0.6 m/s (저풍 시 환기 확보)",
    reason: "저풍일 환기 부족 추정 — 반복 이슈와 정합",
    relatedDiaryEntryIds: ["fd-002"],
    relatedSensorSnapshot: "풍속 0.55 m/s (실외 목업)",
    riskLevel: "medium",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-004",
    targetGreenhouseId: "gh-07",
    targetGreenhouseName: "제7동 · 시험재배",
    targetEquipment: "유동팬",
    proposedCommand: "유동팬 일일 가동 상한 10h → 12h (14–16시 구간)",
    reason: "온도 편차 완화 — 일지 fd-003",
    relatedDiaryEntryIds: ["fd-003"],
    relatedSensorSnapshot: "온도 편차 Δ2.8°C (목업)",
    riskLevel: "high",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-005",
    targetGreenhouseId: "gh-07",
    targetGreenhouseName: "제7동 · 시험재배",
    targetEquipment: "온풍기",
    proposedCommand: "온풍기 ON 임계 15.5°C → 15.0°C (야간 저온 보완)",
    reason: "서편 저온 의심 — 이상상황 일지 연계",
    relatedDiaryEntryIds: ["fd-003"],
    relatedSensorSnapshot: "최저 15.3°C (목업)",
    riskLevel: "high",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-006",
    targetGreenhouseId: "gh-03",
    targetGreenhouseName: "제3동 · 딸기",
    targetEquipment: "분무기",
    proposedCommand: "분무기 펄스 30s ON / 4분 OFF → 25s ON / 4분 OFF",
    reason: "습도·잎 습윤 균형 (목업 시뮬 제안)",
    relatedDiaryEntryIds: ["fd-001"],
    relatedSensorSnapshot: "습도 평균 76% (목업)",
    riskLevel: "medium",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
  {
    id: "cod-007",
    targetGreenhouseId: "gh-07",
    targetGreenhouseName: "제7동 · 시험재배",
    targetEquipment: "알람",
    proposedCommand: "실내 온도 편차 알람 임계 2.0°C → 1.5°C (조기 경보)",
    reason: "온도 편차 이상상황 빈도 증가",
    relatedDiaryEntryIds: ["fd-003"],
    relatedSensorSnapshot: "편차 추세 +0.3°C/일 (목업)",
    riskLevel: "critical",
    status: "draft",
    lastActionAt: null,
    lastActionSummary: null,
  },
];
